from ex4 import Die
die1 = Die(number=2, faces=7)
die2 = Die(number=4, faces=4)
die3 = Die(number=3, faces=12)
die4= Die(number=5, faces= 6)
print(die1, die2, die3, die4)
die1.roll()
die2.roll()
die3.roll()
die4.roll()
print(die1, die2, die3, die4)
die1.roll()
die2.roll()
die3.roll()
die4.roll()
print(die1, die2, die3, die4)